### ISSUE TITLE
Allow users to define nodePorts of services

### ISSUE THREAD

**Issue by apratt3377** [jpmorganchase/qubernetes#24]
Currently when defining quorum services as nodePort type, only the port and targetPort are set.  Kubernetes selects the nodePort that allows external access to the services.  Allowing users to choose nodePorts will provide further customization to the project

**Comment by libby** [comment]
Closing for now, as adding NodePorts might have conflicts with running ports and they would need to be incremented without running into conflicts, we could add a CLI helper to extract the NodePorts from a running network.
