### ISSUE TITLE
[Error]  pull access denied for jpmorganchase/qubernetes

### ISSUE THREAD

**Issue by marvin-hansen** [jpmorganchase/qubernetes#3]
When trying out the bootstrap container, the following error occurs:

```
docker run -ti jpmorganchase/qubernetes
```

> Unable to find image 'jpmorganchase/qubernetes:latest' locally
> docker: Error response from daemon: pull access denied for jpmorganchase/qubernetes, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

A quick look at dockerhub confirms, indeed, that there is no matching public repo.

Has the repo changed or is the bootstrap container just gone?

**Comment by libby** [comment]
Hey @marvin-hansen sorry the dockerhub repo was incorrect. I've pushed the docker image to quorumengineering (dockerhub) https://hub.docker.com/repository/docker/quorumengineering/qubernetes and updated the README.md accordingly. Let me know if that works for you.

**Comment by marvin-hansen** [comment]
Thank you @libby 

yes, the bootstrap container works fine. Please add it at the top of the README because installing and fixing all dependencies manually takes just too much time. 

Anyway, thank your speedy resolution of the issue.

**Comment by libby** [comment]
Great! Glad it works :) yeah, I'm revamping/updating the examples and the README.md, I'll update it in the next day(ish).

**Comment by marvin-hansen** [comment]
It doesn't work.

Just the reported issues have been fixed, which is great, but I had to fill
the next issue because the generated files fail to deploy. Looks like the
file generator needs some tweaking.

I give it a second look after the next update.

Thanks for your help

M
