### ISSUE TITLE
 error parsing out\01-quorum-shared-config.yaml: error converting YAML to JSON: yaml: line 5: mapping values are n ot allowed in this context

### ISSUE THREAD

**Issue by marvin-hansen** [jpmorganchase/qubernetes#5]
Ok, 

generated a set of deployment files from a slightly modified config from the examples by using the Docker container, tried a deployment, and got the following error:

``
 error parsing out\01-quorum-shared-config.yaml: error converting YAML to JSON: yaml: line 5: mapping values are not allowed in this context
``

When I did a diff with the working seven node example, I noticed that the generator creates one more file, which seems to have been merged in the 7 nodes examples. So, I replicated the exact same merge but without success.

Files attached. 

Is there any practical way deploy the generated files on K8s? 
  

[gkes-gen.zip](https://github.com/jpmorganchase/qubernetes/files/4027565/gkes-gen.zip)

**Comment by libby** [comment]
This should be fixed with https://github.com/jpmorganchase/qubernetes/commit/3219625c4f1db9486415cbe8551a05a2cb530222. I ran into it too while re-generating the 7nodes examples. Setting the Namespace is optional and going forward leaving the namespace out and setting when applying the k8s resources will be the suggested way (I'll be updating the README in the next couple days).

**Comment by marvin-hansen** [comment]
@libby you are the hero of the day!

That did the trick so our k8s deployment is up & running. 

When you update things, would you please update the docker container as well? 
  
Thank you so much. You're doing an amazing job!

**Comment by libby** [comment]
Great! @marvin-hansen  FTW :) Also if you have any questions, comments, requests, slack is a good place to ask them. Out of curiosity which K8s platform are you deploying to? A cloud service provider, your own installation, minikube?

**Comment by marvin-hansen** [comment]
@libby Everything on GCP. We got a large voucher from Google for about 3 months of free usage... 
 
I am architecting a unified data, compute & ML graph with everything uniformly accessible via GraphQL. Thus, integrating Quroum into the unified will be done by using a microservice for wrapping its REST interface to GraphQL until Quroum for the time being.  I think somebody said on the Slack Channel that GraphQL is on the 2020 Roadmap. 

As background, I am working for a startup that tackles insurance in Indonesia, a country of some 264 million people so naturally online systems required auto-scaling.
